### PR TITLE
SEP-0001: SEP Purpose and Guidelines

### PR DESCRIPTION
**Pull request by swissm1ss**

### CODE REVIEW

**Comment by di-menchy** [comment]
IYKYK

**Comment by vVito69** [comment]
yN

**Comment by LucianGnn** [comment]
y

**Comment by NativoDave** [comment]
****1

**Comment by Kir799** [comment]
Hehey! Full speed ahead!

**Review by sclue — COMMENTED** [review]
Issue template line 6: what are the guidelines? 
line 10: Soft primitives, do we need examples here or elsewhere? 
Pull request template
line 3: are we going to have a bot that will allow auto pr merge?? 
REadME:
line3: Is this list appropriate? Should be more in line with the white paper, correct? 
Maybe: Steward On-chain primitives, Support Core teams, Manage the Treasury?
like 12: URL needs updated still reads: research.synthetix.io
line 16: Is soft counsel going to be voted in? If yes/no who are the counsel members, what qualifies them? 
line 18: Is super majority vote required. Based on research, it is normal to have very low participation in voting so perhaps a different approach is required. 
20: Should we pay a bounty, if so should we pay in SOFT vs sUSD? 
28/29: Again super majority

**Comment by onchainbarryallen** [comment]
@sclue suggested edits have been made ✅

**Pull request merged**
